# Generated by Django 4.0.1 on 2022-02-01 17:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_administrator_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('brand', models.CharField(max_length=89, unique=True, verbose_name='brand')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
            ],
            options={
                'verbose_name_plural': 'Tracking Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('category', models.CharField(max_length=67, unique=True, verbose_name='category')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
            ],
            options={
                'verbose_name_plural': 'Tracking Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('product', models.CharField(max_length=156, verbose_name='product name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Bisexual', 'Bisexual')], max_length=15, verbose_name='gender')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('price', models.FloatField(verbose_name='price')),
                ('discount_price', models.FloatField(default=0.0, verbose_name='discount price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('size', models.FloatField(verbose_name='shoe size')),
                ('color', models.CharField(max_length=20, verbose_name='shoe color')),
                ('number_of_pairs', models.PositiveIntegerField(default=0, verbose_name='number of pairs')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.administrator')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'Tracking Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinLengthValidator(0)], verbose_name='rating')),
                ('review', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Tracking Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('ordered', models.BooleanField(default=False, verbose_name='quantity')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('total_price', models.FloatField(default=0.0, verbose_name='total price')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Tracking Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('ordered', models.BooleanField(default=False, verbose_name='ordered')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('total_price', models.FloatField(default=0.0, verbose_name='total price')),
                ('date_ordered', models.DateTimeField(verbose_name='date ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('product', models.ManyToManyField(to='shop.OrderItem')),
            ],
            options={
                'verbose_name_plural': 'Tracking Model',
                'abstract': False,
            },
        ),
    ]
