# Generated by Django 4.0.1 on 2022-07-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='added_by',
        ),
    ]
